# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoringsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
